### ISSUE TITLE
Found out about this so ill put a score why not

### ISSUE THREAD

**Issue by anexistantperson** [noatpad/wow-your-friends#1]
https://steamcommunity.com/sharedfiles/filedetails/?id=1988151857
Done on February 3rd 2020 by Clantis (I need a better name ;-;)

From what I know on this file: Assist or variants has never been enabled, Debug mode was disabled at the time of getting the berry, And the only save file editing I've done to it is wiping speedrun records because I literally had like a 30 second 5b run from ghostnet teleporting lol.

Farewell berry was the final berry - No memes

There's a small chance ill redo the farewell berry just for a video but for now I have no valid proof of doing it.

**Comment by noatpad** [comment]
Good luck if you do go for the video. I've had about 1 or 2 who's done something similar in the past, so it's not out of the realm of possibility.

If you can, can you send me a screenshot of your journal stats (preferably as early as when you got the berry)? It can help validate a few things, plus when it comes to that "non-verified" category, that journal screenshot is what I use to link a runner's entry to

**Comment by anexistantperson** [comment]
I assume you mean the main page of it https://steamcommunity.com/sharedfiles/filedetails/?id=2001963277

Sadly I never thought to get one after the berry though.

**Comment by noatpad** [comment]
Yeah that one! And this'll do; the stats definitely line up well with others who have gotten the berry, so I can put this in the non-verified section~.

Gimme a few hours to be able to update the list and push the changes

**Comment by noatpad** [comment]
Pardon the late response, but I just updated the site and it should be good to look now. Just see that “non-verified” checkbox, & you’ll be right down there.

Congrats to ya for getting the berry!~
