### ISSUE TITLE
I did it!

### ISSUE THREAD

**Issue by Piper1618** [noatpad/wow-your-friends#2]
I completed the Farewell golden strawberry on February 14th.

[Video proof](https://youtu.be/lSFeRg5Uo5o)

I'm [Piper1618](https://www.twitch.tv/piper1618) on Twitch

This was the last berry. No memes.

Thanks for your time putting all this together!

**Comment by noatpad** [comment]
Ah, sorry for the late reply, but I just checked the video, & it looks good to go!

I updated the list not too long ago, and the site should reflect the changes now. Huge congrats to you for getting it done!~
