### ISSUE TITLE
I rebeat it with a video

### ISSUE THREAD

**Issue by anexistantperson** [noatpad/wow-your-friends#3]
Im not going to make a huge description like last time,
https://youtu.be/nZIkxLvDL6s
Clantis
debug off assist off and everest uninstalled, if something is wrong with everywhere before the golden room that makes the video unverifiable i also showed everest was uninstalled and stuff before stoping the video.

This rerun didn't even take 6 hours lol.

**Comment by noatpad** [comment]
Oh wow, the fact that you got this in under 6 hours _and_ survived some risky strats is something else. Everything looks good to go, so you're officially verified on this~. Well done to get this done, no joke.

The site should be updated with your name on the verified status in a few minutes~
