### ISSUE TITLE
Celeste Farewell Golden Strawberry (FWG) Completion

### ISSUE THREAD

**Issue by Probatus77** [noatpad/wow-your-friends#37]
Hello,

I completed FWG on July 7th and was hoping to have my run verified and logged on the spreadsheet.  Here is my FWG run: https://youtu.be/lbhLsvKhEQo

I go by Probatus on Steam and would prefer to use that name for the spreadsheet.  Please let me know if you need anything else and thank you very much for managing the spreadsheet that probably inspires others to complete the challenge.

Regards,
Probatus

**Comment by noatpad** [comment]
Hi there! A lil late to this, but your run is good to go and I am about to update the site in a few minutes! A huge congrats to ya for getting the berry!!

**Comment by Probatus77** [comment]
Thank you!!
