### ISSUE TITLE
Got 202 berries (fwg run)

### ISSUE THREAD

**Issue by ynok7** [noatpad/wow-your-friends#43]
Hello, I got the fwg on October 9th, which was the last berry to get (got 202 berries). I go by "Yuunoko".

Here's my run on video: https://youtu.be/CEbBZpMhccM?si=CGcr74cL8E21QROb

Thanks for your dedication maintaining this list.

**Comment by noatpad** [comment]
Entry added! So sorry I took a long time to get to this, but you're now on the list! Congrats!
