### ISSUE TITLE
First switch Milestone year should be 2019, not 2020

### ISSUE THREAD

**Issue by RedFlames** [noatpad/wow-your-friends#5]
Hi!

First of all, this site looks phenomenal, gg! But I've noticed an issue on your site:

#### In the milestones section we have:
- Dec 25, 2019  -- _[...]_
- **Dec 28, 2020**  -- The first 202 on Switch was achieved!
- Jan 25, 2020  --  _[...]_

#### In the list of 202s the first Switch entry is here:
- 24th | Mozkovic | **Dec 28, 2019** | Switch |  -
- 25th | Habbedaz | Jan 11, 2020 | PC |  -

It looks like in commit https://github.com/noatpad/wow-your-friends/commit/22bee3cb9cfd63e7592b7954645be409ffcbad5d you had accidentally used Habbedaz' date before and fixed it, but forgot to change the **2020** to a **2019** :)

Cheers! 🍓 

https://github.com/noatpad/wow-your-friends/blob/e620892e3d9d268f63e8bf3e515546e97ccf9940/src/components/Milestones.jsx#L153

**Comment by noatpad** [comment]
Whoop, sorry that this took a while to address. I kinda procrastinated on updating the site as of late. But I just made a lil' mega-update today and it should be all good now! Thanks for letting me know about this typo of mine
