### ISSUE TITLE
Got 202 berries / update needed

### ISSUE THREAD

**Issue by Kokasgui** [noatpad/wow-your-friends#6]
Hi! First of all, WOW! Amazing work you've all done! Thank you for making this amazing list!
Second, I got the FWG two days ago (posted progress & screenshots at the Celestecord) and I'm in DJTom's list but not on yours, which brings me to...
Third, the list is quite out of date, with the most recent entry being in August 2021 (if I'm not mistaken), so it would be cool if you showed to the most recent runs.

Kokasgui

**Comment by noatpad** [comment]
Hey there! I just updated the site once more _(after a few months of procrastination, ahah)_, and not only have I been able to get it updated alongside the FWG spreadsheet, but I also found your records on the Celestecord and can say you're now part of the list!
Everything should be good on the site now, so congrats on getting every Celeste berry!~
