### ISSUE TITLE
Yay

### ISSUE THREAD

**Issue by esawady** [noatpad/wow-your-friends#7]
https://spacepub.space/w/gRfFNQGpc1aLYyvhaJsTMf

(I'd also appreciate it if you could pass this along to whoever maintains the spreadsheet - I don't have a Discord account)

Edit: I'd also like to be put in as ecs, rather than esawady

**Comment by noatpad** [comment]
Just checked and updated the list with your entry. Pardon for the _very_ late check, but welcome to the club~

**Comment by esawady** [comment]
By the way, this was on Linux, not PC
