### ISSUE TITLE
Update the list based on fwg collectors list

### ISSUE THREAD

**Issue by AuroraKy** [noatpad/wow-your-friends#9]
Hello it's been a while since you last updated the list, a few more people have gotten the berry since then (including me :D)

Could you consider updating the list again?

Here is my berry: https://www.youtube.com/watch?v=AaXIPHmi5Vk (I did somewhat of a funny run, tho I don't think it's as bad as eenox's)

**Comment by noatpad** [comment]
Hi! So sorry that it took me a _very_ long time to get back to you on this. Procrastination and dev environment problems over the months did not help me at all to keep this list up to date, ahah.

But I'm happy to say that the runs ranging from Nov 2022 - Jun 2023 should all be up on the list and synced up with the FWG Collectors spreadsheet; with your run in particular at 346th place. Pardon again for the long delay, though I send my belated congrats to ya nonetheless!!
